# Define a dictionary of quiz areas with their
# corresponding questions, options, and correct answers
quiz_areas = {
    "ML/AI": [
        {"question": "Which algorithm is commonly used for classification tasks in machine learning and AI?",
         "options": ["A. K-Means", "B. Linear Regression", "C. Decision Trees", "D. Principal Component Analysis"],
         "answer": "C"},
        {"question": "Which type of machine learning task involves predicting a continuous outcome?",
         "options": ["A. Classification", "B. Regression", "C. Clustering", "D. Reinforcement Learning"],
         "answer": "B"},
        {"question": "What does the term 'supervised learning' refer to in machine learning?",
         "options": ["A. Learning with labeled data", "B. Learning with a teacher or supervisor", "C. Learning with minimal guidance", "D. Learning in a classroom setting"],
         "answer": "A"},
        {"question": "Which programming language is widely used for machine learning and AI?",
         "options": ["A. C++", "B. Ruby", "C. Java", "D. Python"],
         "answer": "D"},
        {"question": "In the context of natural language processing, what is TF-IDF used for?",
         "options": ["A. Document similarity", "B. Text classification", "C. Named entity recognition", "D. Text summarization"],
         "answer": "A"},
    ],
    "DevOps": [
        {"question": "Which of these is a source code management tool?",
         "options": ["A. Jenkins", "B. Git", "C. Hudson", "D. Maven"],
         "answer": "B"},
        {"question": "Which of these is not a part of the data structure of a Git repository?",
         "options": ["A. Body element", "B. Branch pointer", "C. Commit object", "D. Head pointer"],
         "answer": "A"},
        {"question": "What type of software testing uses JUnit with Java?",
         "options": ["A. System testing", "B. Integration testing", "C. Unit testing", "D. Functional testing"],
         "answer": "C"},
        {"question": "Which tool is commonly used for CI/CD?",
         "options": ["A. Jenkins", "B. Git", "C. Ansible", "D. Docker"],
         "answer": "A"},
        {"question": "In Unix systems, ___ command deletes a directory?",
         "options": ["A. del", "B. deldir", "C. rmdir", "D. rm"],
         "answer": "C"},
    ],
    "Cyber Security": [
        {"question": "Which of these is a type of antivirus program?",
         "options": ["A. Kaspersky", "B. McAfee", "C. Quick heal", "D. All of the above"],
         "answer": "D"},
        {"question": '"Shodan" in cybersecurity is a/an ____',
         "options": ["A. search engine for internet-connected devices", "B. type of malware", "C. cryptographic algorithm", "D. intrusion detection system"],
         "answer": "A"},
        {"question": "What does a Virtual Private Network do?",
         "options": ["A. Monitors network traffic", "B. Increases computer storage", "C. Secures and encrypts internet connections", "D. Deletes unnecessary files"],
         "answer": "C"},
        {"question": "The purpose of a Security Token in multi-factor authentication is to _____?",
         "options": ["A. increase internet speed", "B. encrypt files on the network", "C. generate one-time passwords", "D. conduct security audits"],
         "answer": "C"},
        {"question": "The purpose of a honey pot is to ____?",
         "options": ["A. store encrypted passwords", "B. attract and detect attackers", "C. filter spam emails", "D. optimize network speed"],
         "answer": "B"},
    ],
    "Web Development": [
        {"question": "CGI stands for _____?",
        "options": ["A. Command Gate Interface", "B. Commit to Git Internet", "C. Common Gateway Interface", "D. Common Gate Input"],
        "answer": "C"},
        {"question": "Which of these is NOT a frontend technology?",
        "options": ["A. NodeJS", "B. ReactJS", "C. HTML", "D. Vue"],
        "answer": "A"},
        {"question": "Which HTML5 tag is used for creating hyperlinks?",
        "options": ["A. <link>", "B. <hlink>", "C. <a>", "D. <url>"],
        "answer": "C"},
        {"question": "In React, what does the term 'props' stand for?",
        "options": ["A. Procedures", "B. Properties", "C. Prototypes", "D. Parameters"],
        "answer": "B"},
        {"question": "How can you retrieve unique values from a column in MySQL?",
        "options": ["A. SELECT UNIQUE(column_name)", "B. SELECT DISTINCT column_name", "C. SELECT UNIQUE VALUES(column_name)", "D. SELECT DISTINCT VALUES(column_name)"],
        "answer": "B"},
    ]
}
